name: Frontend Deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # Usa o mesmo segredo que criaste antes!
          aws-region: eu-west-3

      - name: Deploy to S3
        run: aws s3 sync . s3://afonsom.dev-054014031190-eu-west-3-an --delete --exclude ".git/*" --exclude ".github/*"

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2094VPW8D8I3E --paths "/*"